//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsCotizacion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cotizacion", Namespace="http://tempuri.org/")]
    public partial class Cotizacion : object
    {
        
        private System.DateTime fechaField;
        
        private decimal cotizacionField;
        
        private decimal cotizacionOficialField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public decimal cotizacion
        {
            get
            {
                return this.cotizacionField;
            }
            set
            {
                this.cotizacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal cotizacionOficial
        {
            get
            {
                return this.cotizacionOficialField;
            }
            set
            {
                this.cotizacionOficialField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsCotizacion.wsCotizacionSoap")]
    public interface wsCotizacionSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento obtenerCotizacionResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        wsCotizacion.obtenerCotizacionResponse obtenerCotizacion(wsCotizacion.obtenerCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<wsCotizacion.obtenerCotizacionResponse> obtenerCotizacionAsync(wsCotizacion.obtenerCotizacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cotizacion del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCotizacion", ReplyAction="*")]
        wsCotizacion.registrarCotizacionResponse registrarCotizacion(wsCotizacion.registrarCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<wsCotizacion.registrarCotizacionResponse> registrarCotizacionAsync(wsCotizacion.registrarCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public wsCotizacion.obtenerCotizacionRequestBody Body;
        
        public obtenerCotizacionRequest()
        {
        }
        
        public obtenerCotizacionRequest(wsCotizacion.obtenerCotizacionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime Fecha;
        
        public obtenerCotizacionRequestBody()
        {
        }
        
        public obtenerCotizacionRequestBody(System.DateTime Fecha)
        {
            this.Fecha = Fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsCotizacion.obtenerCotizacionResponseBody Body;
        
        public obtenerCotizacionResponse()
        {
        }
        
        public obtenerCotizacionResponse(wsCotizacion.obtenerCotizacionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsCotizacion.Cotizacion obtenerCotizacionResult;
        
        public obtenerCotizacionResponseBody()
        {
        }
        
        public obtenerCotizacionResponseBody(wsCotizacion.Cotizacion obtenerCotizacionResult)
        {
            this.obtenerCotizacionResult = obtenerCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCotizacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public wsCotizacion.registrarCotizacionRequestBody Body;
        
        public registrarCotizacionRequest()
        {
        }
        
        public registrarCotizacionRequest(wsCotizacion.registrarCotizacionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCotizacionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime Fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cotizacion;
        
        public registrarCotizacionRequestBody()
        {
        }
        
        public registrarCotizacionRequestBody(System.DateTime Fecha, string Cotizacion)
        {
            this.Fecha = Fecha;
            this.Cotizacion = Cotizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCotizacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsCotizacion.registrarCotizacionResponseBody Body;
        
        public registrarCotizacionResponse()
        {
        }
        
        public registrarCotizacionResponse(wsCotizacion.registrarCotizacionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCotizacionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrarCotizacionResult;
        
        public registrarCotizacionResponseBody()
        {
        }
        
        public registrarCotizacionResponseBody(string registrarCotizacionResult)
        {
            this.registrarCotizacionResult = registrarCotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface wsCotizacionSoapChannel : wsCotizacion.wsCotizacionSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class wsCotizacionSoapClient : System.ServiceModel.ClientBase<wsCotizacion.wsCotizacionSoap>, wsCotizacion.wsCotizacionSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsCotizacionSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsCotizacionSoapClient.GetBindingForEndpoint(endpointConfiguration), wsCotizacionSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsCotizacionSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsCotizacionSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsCotizacionSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsCotizacionSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsCotizacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsCotizacion.obtenerCotizacionResponse wsCotizacion.wsCotizacionSoap.obtenerCotizacion(wsCotizacion.obtenerCotizacionRequest request)
        {
            return base.Channel.obtenerCotizacion(request);
        }
        
        public wsCotizacion.Cotizacion obtenerCotizacion(System.DateTime Fecha)
        {
            wsCotizacion.obtenerCotizacionRequest inValue = new wsCotizacion.obtenerCotizacionRequest();
            inValue.Body = new wsCotizacion.obtenerCotizacionRequestBody();
            inValue.Body.Fecha = Fecha;
            wsCotizacion.obtenerCotizacionResponse retVal = ((wsCotizacion.wsCotizacionSoap)(this)).obtenerCotizacion(inValue);
            return retVal.Body.obtenerCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsCotizacion.obtenerCotizacionResponse> wsCotizacion.wsCotizacionSoap.obtenerCotizacionAsync(wsCotizacion.obtenerCotizacionRequest request)
        {
            return base.Channel.obtenerCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsCotizacion.obtenerCotizacionResponse> obtenerCotizacionAsync(System.DateTime Fecha)
        {
            wsCotizacion.obtenerCotizacionRequest inValue = new wsCotizacion.obtenerCotizacionRequest();
            inValue.Body = new wsCotizacion.obtenerCotizacionRequestBody();
            inValue.Body.Fecha = Fecha;
            return ((wsCotizacion.wsCotizacionSoap)(this)).obtenerCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsCotizacion.registrarCotizacionResponse wsCotizacion.wsCotizacionSoap.registrarCotizacion(wsCotizacion.registrarCotizacionRequest request)
        {
            return base.Channel.registrarCotizacion(request);
        }
        
        public string registrarCotizacion(System.DateTime Fecha, string Cotizacion)
        {
            wsCotizacion.registrarCotizacionRequest inValue = new wsCotizacion.registrarCotizacionRequest();
            inValue.Body = new wsCotizacion.registrarCotizacionRequestBody();
            inValue.Body.Fecha = Fecha;
            inValue.Body.Cotizacion = Cotizacion;
            wsCotizacion.registrarCotizacionResponse retVal = ((wsCotizacion.wsCotizacionSoap)(this)).registrarCotizacion(inValue);
            return retVal.Body.registrarCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsCotizacion.registrarCotizacionResponse> wsCotizacion.wsCotizacionSoap.registrarCotizacionAsync(wsCotizacion.registrarCotizacionRequest request)
        {
            return base.Channel.registrarCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsCotizacion.registrarCotizacionResponse> registrarCotizacionAsync(System.DateTime Fecha, string Cotizacion)
        {
            wsCotizacion.registrarCotizacionRequest inValue = new wsCotizacion.registrarCotizacionRequest();
            inValue.Body = new wsCotizacion.registrarCotizacionRequestBody();
            inValue.Body.Fecha = Fecha;
            inValue.Body.Cotizacion = Cotizacion;
            return ((wsCotizacion.wsCotizacionSoap)(this)).registrarCotizacionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsCotizacionSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsCotizacionSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsCotizacionSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50257/wsCotizacion.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsCotizacionSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50257/wsCotizacion.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsCotizacionSoap,
            
            wsCotizacionSoap12,
        }
    }
}
