//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsPagos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deuda", Namespace="http://tempuri.org/")]
    public partial class Deuda : object
    {
        
        private string IdField;
        
        private string CIField;
        
        private string FechaField;
        
        private string MontoField;
        
        private string EmpresaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CI
        {
            get
            {
                return this.CIField;
            }
            set
            {
                this.CIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsPagos.PagosSoap")]
    public interface PagosSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerDeuda", ReplyAction="*")]
        WsPagos.VerDeudaResponse VerDeuda(WsPagos.VerDeudaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerDeuda", ReplyAction="*")]
        System.Threading.Tasks.Task<WsPagos.VerDeudaResponse> VerDeudaAsync(WsPagos.VerDeudaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento c del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagarDeuda", ReplyAction="*")]
        WsPagos.PagarDeudaResponse PagarDeuda(WsPagos.PagarDeudaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagarDeuda", ReplyAction="*")]
        System.Threading.Tasks.Task<WsPagos.PagarDeudaResponse> PagarDeudaAsync(WsPagos.PagarDeudaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerDeudaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerDeuda", Namespace="http://tempuri.org/", Order=0)]
        public WsPagos.VerDeudaRequestBody Body;
        
        public VerDeudaRequest()
        {
        }
        
        public VerDeudaRequest(WsPagos.VerDeudaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerDeudaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PrimerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SegundoApellido;
        
        public VerDeudaRequestBody()
        {
        }
        
        public VerDeudaRequestBody(string CI, string Nombres, string PrimerApellido, string SegundoApellido)
        {
            this.CI = CI;
            this.Nombres = Nombres;
            this.PrimerApellido = PrimerApellido;
            this.SegundoApellido = SegundoApellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerDeudaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerDeudaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WsPagos.VerDeudaResponseBody Body;
        
        public VerDeudaResponse()
        {
        }
        
        public VerDeudaResponse(WsPagos.VerDeudaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerDeudaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WsPagos.Deuda[] VerDeudaResult;
        
        public VerDeudaResponseBody()
        {
        }
        
        public VerDeudaResponseBody(WsPagos.Deuda[] VerDeudaResult)
        {
            this.VerDeudaResult = VerDeudaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarDeudaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarDeuda", Namespace="http://tempuri.org/", Order=0)]
        public WsPagos.PagarDeudaRequestBody Body;
        
        public PagarDeudaRequest()
        {
        }
        
        public PagarDeudaRequest(WsPagos.PagarDeudaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarDeudaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WsPagos.Deuda c;
        
        public PagarDeudaRequestBody()
        {
        }
        
        public PagarDeudaRequestBody(WsPagos.Deuda c)
        {
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarDeudaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarDeudaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WsPagos.PagarDeudaResponseBody Body;
        
        public PagarDeudaResponse()
        {
        }
        
        public PagarDeudaResponse(WsPagos.PagarDeudaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PagarDeudaResponseBody
    {
        
        public PagarDeudaResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface PagosSoapChannel : WsPagos.PagosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class PagosSoapClient : System.ServiceModel.ClientBase<WsPagos.PagosSoap>, WsPagos.PagosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PagosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PagosSoapClient.GetBindingForEndpoint(endpointConfiguration), PagosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PagosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PagosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsPagos.VerDeudaResponse WsPagos.PagosSoap.VerDeuda(WsPagos.VerDeudaRequest request)
        {
            return base.Channel.VerDeuda(request);
        }
        
        public WsPagos.Deuda[] VerDeuda(string CI, string Nombres, string PrimerApellido, string SegundoApellido)
        {
            WsPagos.VerDeudaRequest inValue = new WsPagos.VerDeudaRequest();
            inValue.Body = new WsPagos.VerDeudaRequestBody();
            inValue.Body.CI = CI;
            inValue.Body.Nombres = Nombres;
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            WsPagos.VerDeudaResponse retVal = ((WsPagos.PagosSoap)(this)).VerDeuda(inValue);
            return retVal.Body.VerDeudaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsPagos.VerDeudaResponse> WsPagos.PagosSoap.VerDeudaAsync(WsPagos.VerDeudaRequest request)
        {
            return base.Channel.VerDeudaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsPagos.VerDeudaResponse> VerDeudaAsync(string CI, string Nombres, string PrimerApellido, string SegundoApellido)
        {
            WsPagos.VerDeudaRequest inValue = new WsPagos.VerDeudaRequest();
            inValue.Body = new WsPagos.VerDeudaRequestBody();
            inValue.Body.CI = CI;
            inValue.Body.Nombres = Nombres;
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            return ((WsPagos.PagosSoap)(this)).VerDeudaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsPagos.PagarDeudaResponse WsPagos.PagosSoap.PagarDeuda(WsPagos.PagarDeudaRequest request)
        {
            return base.Channel.PagarDeuda(request);
        }
        
        public void PagarDeuda(WsPagos.Deuda c)
        {
            WsPagos.PagarDeudaRequest inValue = new WsPagos.PagarDeudaRequest();
            inValue.Body = new WsPagos.PagarDeudaRequestBody();
            inValue.Body.c = c;
            WsPagos.PagarDeudaResponse retVal = ((WsPagos.PagosSoap)(this)).PagarDeuda(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsPagos.PagarDeudaResponse> WsPagos.PagosSoap.PagarDeudaAsync(WsPagos.PagarDeudaRequest request)
        {
            return base.Channel.PagarDeudaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsPagos.PagarDeudaResponse> PagarDeudaAsync(WsPagos.Deuda c)
        {
            WsPagos.PagarDeudaRequest inValue = new WsPagos.PagarDeudaRequest();
            inValue.Body = new WsPagos.PagarDeudaRequestBody();
            inValue.Body.c = c;
            return ((WsPagos.PagosSoap)(this)).PagarDeudaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PagosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PagosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PagosSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63547/Pagos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PagosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63547/Pagos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PagosSoap,
            
            PagosSoap12,
        }
    }
}
