//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsPersona
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    public partial class Persona : object
    {
        
        private int IDField;
        
        private string CiField;
        
        private string NombresField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ci
        {
            get
            {
                return this.CiField;
            }
            set
            {
                this.CiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsPersona.wsPersonaSoap")]
    public interface wsPersonaSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento persona del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarPersona", ReplyAction="*")]
        wsPersona.InsertarPersonaResponse InsertarPersona(wsPersona.InsertarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<wsPersona.InsertarPersonaResponse> InsertarPersonaAsync(wsPersona.InsertarPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPersona", ReplyAction="*")]
        wsPersona.ObtenerPersonaResponse ObtenerPersona(wsPersona.ObtenerPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<wsPersona.ObtenerPersonaResponse> ObtenerPersonaAsync(wsPersona.ObtenerPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListarPersonasResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPersonas", ReplyAction="*")]
        wsPersona.ListarPersonasResponse ListarPersonas(wsPersona.ListarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPersonas", ReplyAction="*")]
        System.Threading.Tasks.Task<wsPersona.ListarPersonasResponse> ListarPersonasAsync(wsPersona.ListarPersonasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento persona del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarPersona", ReplyAction="*")]
        wsPersona.ActualizarPersonaResponse ActualizarPersona(wsPersona.ActualizarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<wsPersona.ActualizarPersonaResponse> ActualizarPersonaAsync(wsPersona.ActualizarPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPersona", ReplyAction="*")]
        wsPersona.EliminarPersonaResponse EliminarPersona(wsPersona.EliminarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<wsPersona.EliminarPersonaResponse> EliminarPersonaAsync(wsPersona.EliminarPersonaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarPersona", Namespace="http://tempuri.org/", Order=0)]
        public wsPersona.InsertarPersonaRequestBody Body;
        
        public InsertarPersonaRequest()
        {
        }
        
        public InsertarPersonaRequest(wsPersona.InsertarPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarPersonaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsPersona.Persona persona;
        
        public InsertarPersonaRequestBody()
        {
        }
        
        public InsertarPersonaRequestBody(wsPersona.Persona persona)
        {
            this.persona = persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsPersona.InsertarPersonaResponseBody Body;
        
        public InsertarPersonaResponse()
        {
        }
        
        public InsertarPersonaResponse(wsPersona.InsertarPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarPersonaResult;
        
        public InsertarPersonaResponseBody()
        {
        }
        
        public InsertarPersonaResponseBody(string InsertarPersonaResult)
        {
            this.InsertarPersonaResult = InsertarPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPersona", Namespace="http://tempuri.org/", Order=0)]
        public wsPersona.ObtenerPersonaRequestBody Body;
        
        public ObtenerPersonaRequest()
        {
        }
        
        public ObtenerPersonaRequest(wsPersona.ObtenerPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPersonaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ObtenerPersonaRequestBody()
        {
        }
        
        public ObtenerPersonaRequestBody(string ci)
        {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsPersona.ObtenerPersonaResponseBody Body;
        
        public ObtenerPersonaResponse()
        {
        }
        
        public ObtenerPersonaResponse(wsPersona.ObtenerPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsPersona.Persona ObtenerPersonaResult;
        
        public ObtenerPersonaResponseBody()
        {
        }
        
        public ObtenerPersonaResponseBody(wsPersona.Persona ObtenerPersonaResult)
        {
            this.ObtenerPersonaResult = ObtenerPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarPersonasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarPersonas", Namespace="http://tempuri.org/", Order=0)]
        public wsPersona.ListarPersonasRequestBody Body;
        
        public ListarPersonasRequest()
        {
        }
        
        public ListarPersonasRequest(wsPersona.ListarPersonasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarPersonasRequestBody
    {
        
        public ListarPersonasRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarPersonasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarPersonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsPersona.ListarPersonasResponseBody Body;
        
        public ListarPersonasResponse()
        {
        }
        
        public ListarPersonasResponse(wsPersona.ListarPersonasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarPersonasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsPersona.Persona[] ListarPersonasResult;
        
        public ListarPersonasResponseBody()
        {
        }
        
        public ListarPersonasResponseBody(wsPersona.Persona[] ListarPersonasResult)
        {
            this.ListarPersonasResult = ListarPersonasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarPersona", Namespace="http://tempuri.org/", Order=0)]
        public wsPersona.ActualizarPersonaRequestBody Body;
        
        public ActualizarPersonaRequest()
        {
        }
        
        public ActualizarPersonaRequest(wsPersona.ActualizarPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarPersonaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsPersona.Persona persona;
        
        public ActualizarPersonaRequestBody()
        {
        }
        
        public ActualizarPersonaRequestBody(wsPersona.Persona persona)
        {
            this.persona = persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsPersona.ActualizarPersonaResponseBody Body;
        
        public ActualizarPersonaResponse()
        {
        }
        
        public ActualizarPersonaResponse(wsPersona.ActualizarPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActualizarPersonaResult;
        
        public ActualizarPersonaResponseBody()
        {
        }
        
        public ActualizarPersonaResponseBody(string ActualizarPersonaResult)
        {
            this.ActualizarPersonaResult = ActualizarPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarPersona", Namespace="http://tempuri.org/", Order=0)]
        public wsPersona.EliminarPersonaRequestBody Body;
        
        public EliminarPersonaRequest()
        {
        }
        
        public EliminarPersonaRequest(wsPersona.EliminarPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarPersonaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public EliminarPersonaRequestBody()
        {
        }
        
        public EliminarPersonaRequestBody(string ci)
        {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsPersona.EliminarPersonaResponseBody Body;
        
        public EliminarPersonaResponse()
        {
        }
        
        public EliminarPersonaResponse(wsPersona.EliminarPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarPersonaResult;
        
        public EliminarPersonaResponseBody()
        {
        }
        
        public EliminarPersonaResponseBody(string EliminarPersonaResult)
        {
            this.EliminarPersonaResult = EliminarPersonaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface wsPersonaSoapChannel : wsPersona.wsPersonaSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class wsPersonaSoapClient : System.ServiceModel.ClientBase<wsPersona.wsPersonaSoap>, wsPersona.wsPersonaSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsPersonaSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsPersonaSoapClient.GetBindingForEndpoint(endpointConfiguration), wsPersonaSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPersonaSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsPersonaSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPersonaSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsPersonaSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPersonaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsPersona.InsertarPersonaResponse wsPersona.wsPersonaSoap.InsertarPersona(wsPersona.InsertarPersonaRequest request)
        {
            return base.Channel.InsertarPersona(request);
        }
        
        public string InsertarPersona(wsPersona.Persona persona)
        {
            wsPersona.InsertarPersonaRequest inValue = new wsPersona.InsertarPersonaRequest();
            inValue.Body = new wsPersona.InsertarPersonaRequestBody();
            inValue.Body.persona = persona;
            wsPersona.InsertarPersonaResponse retVal = ((wsPersona.wsPersonaSoap)(this)).InsertarPersona(inValue);
            return retVal.Body.InsertarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsPersona.InsertarPersonaResponse> wsPersona.wsPersonaSoap.InsertarPersonaAsync(wsPersona.InsertarPersonaRequest request)
        {
            return base.Channel.InsertarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsPersona.InsertarPersonaResponse> InsertarPersonaAsync(wsPersona.Persona persona)
        {
            wsPersona.InsertarPersonaRequest inValue = new wsPersona.InsertarPersonaRequest();
            inValue.Body = new wsPersona.InsertarPersonaRequestBody();
            inValue.Body.persona = persona;
            return ((wsPersona.wsPersonaSoap)(this)).InsertarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsPersona.ObtenerPersonaResponse wsPersona.wsPersonaSoap.ObtenerPersona(wsPersona.ObtenerPersonaRequest request)
        {
            return base.Channel.ObtenerPersona(request);
        }
        
        public wsPersona.Persona ObtenerPersona(string ci)
        {
            wsPersona.ObtenerPersonaRequest inValue = new wsPersona.ObtenerPersonaRequest();
            inValue.Body = new wsPersona.ObtenerPersonaRequestBody();
            inValue.Body.ci = ci;
            wsPersona.ObtenerPersonaResponse retVal = ((wsPersona.wsPersonaSoap)(this)).ObtenerPersona(inValue);
            return retVal.Body.ObtenerPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsPersona.ObtenerPersonaResponse> wsPersona.wsPersonaSoap.ObtenerPersonaAsync(wsPersona.ObtenerPersonaRequest request)
        {
            return base.Channel.ObtenerPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsPersona.ObtenerPersonaResponse> ObtenerPersonaAsync(string ci)
        {
            wsPersona.ObtenerPersonaRequest inValue = new wsPersona.ObtenerPersonaRequest();
            inValue.Body = new wsPersona.ObtenerPersonaRequestBody();
            inValue.Body.ci = ci;
            return ((wsPersona.wsPersonaSoap)(this)).ObtenerPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsPersona.ListarPersonasResponse wsPersona.wsPersonaSoap.ListarPersonas(wsPersona.ListarPersonasRequest request)
        {
            return base.Channel.ListarPersonas(request);
        }
        
        public wsPersona.Persona[] ListarPersonas()
        {
            wsPersona.ListarPersonasRequest inValue = new wsPersona.ListarPersonasRequest();
            inValue.Body = new wsPersona.ListarPersonasRequestBody();
            wsPersona.ListarPersonasResponse retVal = ((wsPersona.wsPersonaSoap)(this)).ListarPersonas(inValue);
            return retVal.Body.ListarPersonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsPersona.ListarPersonasResponse> wsPersona.wsPersonaSoap.ListarPersonasAsync(wsPersona.ListarPersonasRequest request)
        {
            return base.Channel.ListarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsPersona.ListarPersonasResponse> ListarPersonasAsync()
        {
            wsPersona.ListarPersonasRequest inValue = new wsPersona.ListarPersonasRequest();
            inValue.Body = new wsPersona.ListarPersonasRequestBody();
            return ((wsPersona.wsPersonaSoap)(this)).ListarPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsPersona.ActualizarPersonaResponse wsPersona.wsPersonaSoap.ActualizarPersona(wsPersona.ActualizarPersonaRequest request)
        {
            return base.Channel.ActualizarPersona(request);
        }
        
        public string ActualizarPersona(wsPersona.Persona persona)
        {
            wsPersona.ActualizarPersonaRequest inValue = new wsPersona.ActualizarPersonaRequest();
            inValue.Body = new wsPersona.ActualizarPersonaRequestBody();
            inValue.Body.persona = persona;
            wsPersona.ActualizarPersonaResponse retVal = ((wsPersona.wsPersonaSoap)(this)).ActualizarPersona(inValue);
            return retVal.Body.ActualizarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsPersona.ActualizarPersonaResponse> wsPersona.wsPersonaSoap.ActualizarPersonaAsync(wsPersona.ActualizarPersonaRequest request)
        {
            return base.Channel.ActualizarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsPersona.ActualizarPersonaResponse> ActualizarPersonaAsync(wsPersona.Persona persona)
        {
            wsPersona.ActualizarPersonaRequest inValue = new wsPersona.ActualizarPersonaRequest();
            inValue.Body = new wsPersona.ActualizarPersonaRequestBody();
            inValue.Body.persona = persona;
            return ((wsPersona.wsPersonaSoap)(this)).ActualizarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsPersona.EliminarPersonaResponse wsPersona.wsPersonaSoap.EliminarPersona(wsPersona.EliminarPersonaRequest request)
        {
            return base.Channel.EliminarPersona(request);
        }
        
        public string EliminarPersona(string ci)
        {
            wsPersona.EliminarPersonaRequest inValue = new wsPersona.EliminarPersonaRequest();
            inValue.Body = new wsPersona.EliminarPersonaRequestBody();
            inValue.Body.ci = ci;
            wsPersona.EliminarPersonaResponse retVal = ((wsPersona.wsPersonaSoap)(this)).EliminarPersona(inValue);
            return retVal.Body.EliminarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsPersona.EliminarPersonaResponse> wsPersona.wsPersonaSoap.EliminarPersonaAsync(wsPersona.EliminarPersonaRequest request)
        {
            return base.Channel.EliminarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsPersona.EliminarPersonaResponse> EliminarPersonaAsync(string ci)
        {
            wsPersona.EliminarPersonaRequest inValue = new wsPersona.EliminarPersonaRequest();
            inValue.Body = new wsPersona.EliminarPersonaRequestBody();
            inValue.Body.ci = ci;
            return ((wsPersona.wsPersonaSoap)(this)).EliminarPersonaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPersonaSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsPersonaSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPersonaSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50074/wsPersona.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsPersonaSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50074/wsPersona.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsPersonaSoap,
            
            wsPersonaSoap12,
        }
    }
}
