//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srPersona
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    public partial class Persona : object
    {
        
        private string ciField;
        
        private string nameField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ci
        {
            get
            {
                return this.ciField;
            }
            set
            {
                this.ciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primerApellido
        {
            get
            {
                return this.primerApellidoField;
            }
            set
            {
                this.primerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundoApellido
        {
            get
            {
                return this.segundoApellidoField;
            }
            set
            {
                this.segundoApellidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srPersona.wsPersonaSoap")]
    public interface wsPersonaSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crearPersona", ReplyAction="*")]
        srPersona.crearPersonaResponse crearPersona(srPersona.crearPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crearPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<srPersona.crearPersonaResponse> crearPersonaAsync(srPersona.crearPersonaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearPersonaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearPersona", Namespace="http://tempuri.org/", Order=0)]
        public srPersona.crearPersonaRequestBody Body;
        
        public crearPersonaRequest()
        {
        }
        
        public crearPersonaRequest(srPersona.crearPersonaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class crearPersonaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string primerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string segundoApellido;
        
        public crearPersonaRequestBody()
        {
        }
        
        public crearPersonaRequestBody(string ci, string nombre, string primerApellido, string segundoApellido)
        {
            this.ci = ci;
            this.nombre = nombre;
            this.primerApellido = primerApellido;
            this.segundoApellido = segundoApellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crearPersonaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crearPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public srPersona.crearPersonaResponseBody Body;
        
        public crearPersonaResponse()
        {
        }
        
        public crearPersonaResponse(srPersona.crearPersonaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class crearPersonaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public srPersona.Persona crearPersonaResult;
        
        public crearPersonaResponseBody()
        {
        }
        
        public crearPersonaResponseBody(srPersona.Persona crearPersonaResult)
        {
            this.crearPersonaResult = crearPersonaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface wsPersonaSoapChannel : srPersona.wsPersonaSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class wsPersonaSoapClient : System.ServiceModel.ClientBase<srPersona.wsPersonaSoap>, srPersona.wsPersonaSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsPersonaSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsPersonaSoapClient.GetBindingForEndpoint(endpointConfiguration), wsPersonaSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPersonaSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsPersonaSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPersonaSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsPersonaSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPersonaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        srPersona.crearPersonaResponse srPersona.wsPersonaSoap.crearPersona(srPersona.crearPersonaRequest request)
        {
            return base.Channel.crearPersona(request);
        }
        
        public srPersona.Persona crearPersona(string ci, string nombre, string primerApellido, string segundoApellido)
        {
            srPersona.crearPersonaRequest inValue = new srPersona.crearPersonaRequest();
            inValue.Body = new srPersona.crearPersonaRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombre = nombre;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            srPersona.crearPersonaResponse retVal = ((srPersona.wsPersonaSoap)(this)).crearPersona(inValue);
            return retVal.Body.crearPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srPersona.crearPersonaResponse> srPersona.wsPersonaSoap.crearPersonaAsync(srPersona.crearPersonaRequest request)
        {
            return base.Channel.crearPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<srPersona.crearPersonaResponse> crearPersonaAsync(string ci, string nombre, string primerApellido, string segundoApellido)
        {
            srPersona.crearPersonaRequest inValue = new srPersona.crearPersonaRequest();
            inValue.Body = new srPersona.crearPersonaRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.nombre = nombre;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            return ((srPersona.wsPersonaSoap)(this)).crearPersonaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPersonaSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsPersonaSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPersonaSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50775/wsPersona.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsPersonaSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50775/wsPersona.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsPersonaSoap,
            
            wsPersonaSoap12,
        }
    }
}
