//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plataformaPagos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://tempuri.org/")]
    public partial class Factura : object
    {
        
        private string empresaField;
        
        private string nroFacturaField;
        
        private string ciField;
        
        private string nombreCompletoField;
        
        private string periodoField;
        
        private double montoField;
        
        private string estadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string empresa
        {
            get
            {
                return this.empresaField;
            }
            set
            {
                this.empresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nroFactura
        {
            get
            {
                return this.nroFacturaField;
            }
            set
            {
                this.nroFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ci
        {
            get
            {
                return this.ciField;
            }
            set
            {
                this.ciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nombreCompleto
        {
            get
            {
                return this.nombreCompletoField;
            }
            set
            {
                this.nombreCompletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double monto
        {
            get
            {
                return this.montoField;
            }
            set
            {
                this.montoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="plataformaPagos.pagosSoap")]
    public interface pagosSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerDeuda", ReplyAction="*")]
        plataformaPagos.VerDeudaResponse VerDeuda(plataformaPagos.VerDeudaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerDeuda", ReplyAction="*")]
        System.Threading.Tasks.Task<plataformaPagos.VerDeudaResponse> VerDeudaAsync(plataformaPagos.VerDeudaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento facturas del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pagar", ReplyAction="*")]
        plataformaPagos.PagarResponse Pagar(plataformaPagos.PagarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pagar", ReplyAction="*")]
        System.Threading.Tasks.Task<plataformaPagos.PagarResponse> PagarAsync(plataformaPagos.PagarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerDeudaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerDeuda", Namespace="http://tempuri.org/", Order=0)]
        public plataformaPagos.VerDeudaRequestBody Body;
        
        public VerDeudaRequest()
        {
        }
        
        public VerDeudaRequest(plataformaPagos.VerDeudaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerDeudaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public VerDeudaRequestBody()
        {
        }
        
        public VerDeudaRequestBody(string CI)
        {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerDeudaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerDeudaResponse", Namespace="http://tempuri.org/", Order=0)]
        public plataformaPagos.VerDeudaResponseBody Body;
        
        public VerDeudaResponse()
        {
        }
        
        public VerDeudaResponse(plataformaPagos.VerDeudaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerDeudaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public plataformaPagos.Factura[] VerDeudaResult;
        
        public VerDeudaResponseBody()
        {
        }
        
        public VerDeudaResponseBody(plataformaPagos.Factura[] VerDeudaResult)
        {
            this.VerDeudaResult = VerDeudaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Pagar", Namespace="http://tempuri.org/", Order=0)]
        public plataformaPagos.PagarRequestBody Body;
        
        public PagarRequest()
        {
        }
        
        public PagarRequest(plataformaPagos.PagarRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public plataformaPagos.Factura[] facturas;
        
        public PagarRequestBody()
        {
        }
        
        public PagarRequestBody(plataformaPagos.Factura[] facturas)
        {
            this.facturas = facturas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarResponse", Namespace="http://tempuri.org/", Order=0)]
        public plataformaPagos.PagarResponseBody Body;
        
        public PagarResponse()
        {
        }
        
        public PagarResponse(plataformaPagos.PagarResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PagarResponseBody
    {
        
        public PagarResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface pagosSoapChannel : plataformaPagos.pagosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class pagosSoapClient : System.ServiceModel.ClientBase<plataformaPagos.pagosSoap>, plataformaPagos.pagosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public pagosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(pagosSoapClient.GetBindingForEndpoint(endpointConfiguration), pagosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public pagosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(pagosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public pagosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(pagosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public pagosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        plataformaPagos.VerDeudaResponse plataformaPagos.pagosSoap.VerDeuda(plataformaPagos.VerDeudaRequest request)
        {
            return base.Channel.VerDeuda(request);
        }
        
        public plataformaPagos.Factura[] VerDeuda(string CI)
        {
            plataformaPagos.VerDeudaRequest inValue = new plataformaPagos.VerDeudaRequest();
            inValue.Body = new plataformaPagos.VerDeudaRequestBody();
            inValue.Body.CI = CI;
            plataformaPagos.VerDeudaResponse retVal = ((plataformaPagos.pagosSoap)(this)).VerDeuda(inValue);
            return retVal.Body.VerDeudaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<plataformaPagos.VerDeudaResponse> plataformaPagos.pagosSoap.VerDeudaAsync(plataformaPagos.VerDeudaRequest request)
        {
            return base.Channel.VerDeudaAsync(request);
        }
        
        public System.Threading.Tasks.Task<plataformaPagos.VerDeudaResponse> VerDeudaAsync(string CI)
        {
            plataformaPagos.VerDeudaRequest inValue = new plataformaPagos.VerDeudaRequest();
            inValue.Body = new plataformaPagos.VerDeudaRequestBody();
            inValue.Body.CI = CI;
            return ((plataformaPagos.pagosSoap)(this)).VerDeudaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        plataformaPagos.PagarResponse plataformaPagos.pagosSoap.Pagar(plataformaPagos.PagarRequest request)
        {
            return base.Channel.Pagar(request);
        }
        
        public void Pagar(plataformaPagos.Factura[] facturas)
        {
            plataformaPagos.PagarRequest inValue = new plataformaPagos.PagarRequest();
            inValue.Body = new plataformaPagos.PagarRequestBody();
            inValue.Body.facturas = facturas;
            plataformaPagos.PagarResponse retVal = ((plataformaPagos.pagosSoap)(this)).Pagar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<plataformaPagos.PagarResponse> plataformaPagos.pagosSoap.PagarAsync(plataformaPagos.PagarRequest request)
        {
            return base.Channel.PagarAsync(request);
        }
        
        public System.Threading.Tasks.Task<plataformaPagos.PagarResponse> PagarAsync(plataformaPagos.Factura[] facturas)
        {
            plataformaPagos.PagarRequest inValue = new plataformaPagos.PagarRequest();
            inValue.Body = new plataformaPagos.PagarRequestBody();
            inValue.Body.facturas = facturas;
            return ((plataformaPagos.pagosSoap)(this)).PagarAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.pagosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.pagosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.pagosSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:60920/pagos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.pagosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:60920/pagos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            pagosSoap,
            
            pagosSoap12,
        }
    }
}
